"""Fake ADB transport tests only; no showcase PNGs are generated by these tests."""
import importlib.util
import json
from pathlib import Path
import subprocess
import tempfile
import unittest

MODULE = Path(__file__).resolve().parents[1] / 'looloo_screenshots.py'
spec = importlib.util.spec_from_file_location('capture', MODULE)
capture = importlib.util.module_from_spec(spec)
spec.loader.exec_module(capture)


class Transport:
    def __init__(self, outcomes):
        self.outcomes = outcomes
        self.current = None
        self.launched = []
        self.commands = []
        self.cleanup_failure = False
        self.recents = ''

    def instrument(self, screen_id):
        self.current = screen_id
        self.launched.append(screen_id)
        outcome = self.outcomes.get(screen_id, 'captured')
        if outcome == 'interrupted':
            raise KeyboardInterrupt
        if outcome == 'timeout':
            raise subprocess.TimeoutExpired('instrument', 120)
        if outcome == 'reported_failure':
            return subprocess.CompletedProcess([], 1, 'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\njava.lang.AssertionError', '')
        return subprocess.CompletedProcess([], 0, 'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\njava.lang.ClassCastException' if outcome == 'crash' else 'OK (1 test)', '')

    def command(self, *parts, binary=False):
        self.commands.append(parts)
        if self.cleanup_failure and parts[:3] == ('shell', 'am', 'force-stop'):
            raise OSError('disconnected')
        if parts == ('shell', 'dumpsys', 'activity', 'recents'):
            return self.recents
        if parts[0] != 'exec-out':
            return ''
        outcome = self.outcomes.get(self.current, 'captured')
        if parts[-1].endswith('results.json'):
            if outcome in ('crash', 'missing'):
                return '{}'
            if outcome == 'malformed':
                return '{'
            if outcome == 'wrong_id':
                return json.dumps({'other_fixture': {'status': 'captured'}})
            if outcome == 'reported_failure':
                return json.dumps({self.current: {
                    'status': 'failed',
                    'capture_stage': 'restoration_validation',
                    'error_type': 'IllegalStateException',
                    'error_message': 'Restored fixture did not survive its production saver: key',
                    'original_error_type': 'IllegalStateException',
                    'original_error_message': 'Restored fixture did not survive its production saver: key',
                    'detail_log': f'logs/{self.current}.log',
                    'notes': 'fixture failed during restoration validation',
                }})
            return json.dumps({self.current: {'status': 'failed' if outcome == 'failed' else 'captured', 'notes': 'Test transport result'}})
        return b'invalid' if outcome == 'bad_png' else b'\x89PNG\r\n\x1a\nTEST_TRANSPORT_ONLY'


class IsolationTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.output = Path(self.temp.name)
        (self.output / 'tablet').mkdir()
        self.rows = capture.inventory()[:3]

    def tearDown(self):
        self.temp.cleanup()

    def execute(self, transport, rows=None):
        return capture.capture_batch(rows or self.rows, {}, 'tablet', self.output, transport.command, transport.instrument)

    def test_crash_isolated_earlier_png_survives_and_later_runs(self):
        bad = self.rows[1]['id']
        transport = Transport({bad: 'crash'})
        entries = self.execute(transport)
        self.assertEqual(['captured', 'failed', 'captured'], [r['status'] for r in entries])
        self.assertEqual([r['id'] for r in self.rows], transport.launched)
        self.assertIn('ClassCastException', entries[1]['notes'])
        self.assertIn(bad, entries[1]['notes'])
        self.assertEqual('ClassCastException', entries[1]['error_type'])
        self.assertEqual('instrumentation', entries[1]['capture_stage'])
        self.assertEqual('ClassCastException', entries[1]['original_error_type'])
        self.assertIn('ClassCastException', entries[1]['original_error_message'])
        self.assertEqual(f'logs/{bad}.log', entries[1]['detail_log'])
        self.assertIn(b'ClassCastException', (self.output / entries[1]['detail_log']).read_bytes())
        self.assertTrue((self.output / entries[0]['filename']).exists())
        self.assertFalse((self.output / entries[1]['filename']).exists())
        self.assertTrue((self.output / entries[2]['filename']).exists())

    def test_failed_fixture_never_exports_png(self):
        transport = Transport({self.rows[1]['id']: 'failed'})
        entries = self.execute(transport)
        self.assertEqual('failed', entries[1]['status'])
        self.assertIn('original_error_type', entries[1])
        self.assertIn('original_error_message', entries[1])
        self.assertEqual(f'logs/{self.rows[1]["id"]}.log', entries[1]['detail_log'])
        self.assertFalse((self.output / entries[1]['filename']).exists())
        self.assertEqual(2, len(list(self.output.rglob('*.png'))))

    def test_reported_fixture_error_survives_failing_junit_process(self):
        entries = self.execute(Transport({self.rows[1]['id']: 'reported_failure'}))
        failure = entries[1]
        self.assertEqual('failed', failure['status'])
        self.assertEqual('restoration_validation', failure['capture_stage'])
        self.assertEqual('IllegalStateException', failure['error_type'])
        self.assertIn('production saver', failure['error_message'])

    def test_timeout_continues_and_cleanup_runs(self):
        transport = Transport({self.rows[1]['id']: 'timeout'})
        entries = self.execute(transport)
        self.assertEqual('TimeoutExpired', entries[1]['error_type'])
        self.assertEqual('captured', entries[2]['status'])
        self.assertEqual(3, transport.commands.count(('shell', 'am', 'force-stop', capture.PACKAGE)))
        self.assertEqual(3, transport.commands.count(('shell', 'am', 'force-stop', capture.PACKAGE + '.test')))
        self.assertEqual(3, transport.commands.count(('shell', 'input', 'keyevent', 'KEYCODE_HOME')))
        self.assertEqual(3, transport.commands.count(('shell', 'am', 'start', '-a', 'android.intent.action.MAIN',
                                                      '-c', 'android.intent.category.HOME')))

    def test_interrupt_preserves_partial_manifest_and_cleans_up(self):
        transport = Transport({self.rows[1]['id']: 'interrupted'})
        with self.assertRaises(KeyboardInterrupt):
            self.execute(transport)
        entries = json.loads((self.output / 'manifest.json').read_text())['entries']
        self.assertEqual(['captured', 'failed', 'blocked'], [r['status'] for r in entries])
        self.assertEqual('Interrupted', entries[1]['error_type'])
        self.assertTrue((self.output / entries[0]['filename']).exists())
        self.assertEqual(('shell', 'am', 'start', '-a', 'android.intent.action.MAIN',
                          '-c', 'android.intent.category.HOME'), transport.commands[-1])

    def test_cleanup_failure_is_reported_and_does_not_mask_capture(self):
        transport = Transport({})
        transport.cleanup_failure = True
        entries = self.execute(transport)
        self.assertTrue(all(r['status'] == 'captured' for r in entries))
        self.assertTrue(all(r['cleanup'] == 'best_effort_failed' for r in entries))
        self.assertIn(('shell', 'input', 'keyevent', 'KEYCODE_HOME'), transport.commands)

    def test_cleanup_removes_only_instrumentation_empty_activity_task(self):
        transport = Transport({})
        transport.recents = '''
* Recent #0: Task{abc #811 type=standard A=com.nahtygal.olivialooi.test}
  taskId=811 affinity=10486:com.nahtygal.olivialooi.test
  realActivity={com.nahtygal.olivialooi.test/androidx.test.core.app.InstrumentationActivityInvoker$EmptyActivity}
* Recent #1: Task{def #812 type=standard A=com.nahtygal.olivialooi}
  taskId=812 affinity=com.nahtygal.olivialooi
  realActivity={com.nahtygal.olivialooi/.MainActivity}
'''
        self.execute(transport, [self.rows[0]])
        self.assertIn(('shell', 'am', 'stack', 'remove', '811'), transport.commands)
        self.assertNotIn(('shell', 'am', 'stack', 'remove', '812'), transport.commands)

    def test_missing_or_bad_results_do_not_stop_later_fixtures(self):
        for outcome in ('missing', 'malformed', 'wrong_id', 'bad_png'):
            with self.subTest(outcome=outcome):
                entries = self.execute(Transport({self.rows[1]['id']: outcome}))
                self.assertEqual(['captured', 'failed', 'captured'], [r['status'] for r in entries])
                self.assertFalse((self.output / entries[1]['filename']).exists())

    def test_utilities_skip_without_starting_instrumentation(self):
        utility = capture.inventory()[-1]
        transport = Transport({})
        entries = self.execute(transport, [self.rows[0], utility])
        self.assertEqual(['captured', 'skipped'], [r['status'] for r in entries])
        self.assertEqual([self.rows[0]['id']], transport.launched)

    def test_showcase_only_lists_successful_screens(self):
        entries = self.execute(Transport({self.rows[1]['id']: 'crash'}))
        self.assertEqual([entries[0]['filename'], entries[2]['filename']], (self.output / 'showcase_order.txt').read_text().splitlines())
        self.assertFalse(list(self.output.rglob('*.tmp')))

    def test_stale_png_is_removed_for_failed_fixture(self):
        path = self.output / 'tablet' / self.rows[1]['filename']
        path.write_bytes(b'old image')
        self.execute(Transport({self.rows[1]['id']: 'crash'}))
        self.assertFalse(path.exists())
