package com.nahtygal.olivialooi.stories

enum class StoryVisual { SNOWMAN, DUCK, RAINBOW, PUPPY, STAR }
data class StoryPage(val pageNumber: Int, val text: String, val visual: StoryVisual)
data class Story(val id: String, val title: String, val shortDescription: String, val coverVisual: StoryVisual, val pages: List<StoryPage>)

/** Original, bundled stories. No platform, speech, or resource dependencies. */
object StoryCatalog {
    private fun story(id: String, title: String, description: String, visual: StoryVisual, vararg text: String) =
        Story(id, title, description, visual, text.mapIndexed { index, words -> StoryPage(index + 1, words, visual) })
    val stories = listOf(
        story("moonlight_snowman", "Olivia and the Moonlight Snowman", "A warm friendship on a snowy evening.", StoryVisual.SNOWMAN,
            "Olivia looked out at the soft snow. A round snowman stood beside the garden gate, wearing a tiny blue hat.",
            "The moon made his buttons shine. Olivia brought a scarf and wrapped it gently around his snowy shoulders.",
            "LooLoo helped Olivia make a little snow rabbit. They gave it two long ears and a smooth pebble nose.",
            "Next, they made a snow bird beside the rabbit. Now the snowman had two friends to share the moonlight.",
            "Olivia drew a heart in the snow. She waved to her new friends, and their shadows waved across the garden.",
            "Inside, Olivia snuggled under her blanket. Outside, the moon watched over three snowy friends and one small heart until morning."),
        story("yellow_duck", "Eliana and the Little Yellow Duck", "Small acts of kindness beside a pond.", StoryVisual.DUCK,
            "Eliana sat on a blanket beside the pond. A little yellow duck paddled past, making tiny circles in the water.",
            "The duck nudged a leaf with its soft bill. Eliana pointed, and Olivia smiled at the little floating boat.",
            "A breeze carried the leaf toward the grass. Olivia gently pushed it back with a twig while Eliana watched.",
            "The duck followed its leaf around a flower. Two other ducks joined in, and their ripples made a wiggly path.",
            "Eliana clapped her hands softly. The little duck gave a happy quack, then paddled close to its warm duck family.",
            "The sisters waved goodbye to the pond. On the way home, they found a yellow flower as bright as their new friend."),
        story("rainbow_sisters", "Olivia and Eliana’s Rainbow Adventure", "Two sisters make something lovely together.", StoryVisual.RAINBOW,
            "After a little rain, a rainbow stretched over the garden. Olivia and Eliana wondered if they could make a rainbow too.",
            "Olivia found a red ribbon and an orange cloth. Eliana chose a yellow cushion with a big, happy smile.",
            "They laid their colors on a blanket. LooLoo brought a green scarf, and Olivia added a soft blue sock.",
            "One space was still waiting for a color. Eliana reached for her purple bunny, and Olivia tucked it beside the sock.",
            "Their rainbow was small enough to hug. The sisters sat beside it and pointed to each color, one by one.",
            "The sky rainbow faded, but their blanket rainbow stayed. Olivia hugged Eliana, glad that making things together was the brightest part."),
        story("sleepy_puppy", "LooLoo’s Sleepy Puppy", "A soft, slow journey to bedtime.", StoryVisual.PUPPY,
            "LooLoo’s puppy had spent the afternoon playing with a soft ball. Now his little paws were ready for a rest.",
            "He carried the ball to his basket. It rolled onto the rug, so he gave it one last gentle nudge.",
            "Olivia placed a blanket in the basket. Eliana waved goodnight while the puppy turned around to find his favorite spot.",
            "LooLoo sat nearby and took a slow breath. The puppy’s ears relaxed, and his tail grew still against the blanket.",
            "A moonbeam rested on the windowsill. The puppy closed one eye, then the other, listening to the quiet room.",
            "His ball could wait until morning. LooLoo whispered goodnight, and the puppy dreamed of soft grass beneath his little paws."),
        story("little_star", "The Little Star That Couldn’t Sleep", "A quiet sky and a reassuring friend.", StoryVisual.STAR,
            "A little star twinkled above the rooftops. All evening, she had counted windows, clouds, and birds returning to their nests.",
            "Now the sky was quiet, but she still felt wide awake. She asked the moon how to get ready for rest.",
            "The moon smiled and pointed to a drifting cloud. The star watched it float slowly, without hurrying anywhere at all.",
            "She let her light grow soft and small. Below her, Olivia and Eliana were cozy, with their blankets tucked around them.",
            "The moon said that resting could begin with being still. The star stopped counting and simply enjoyed the peaceful sky.",
            "Soon she felt as gentle as a sleepy sigh. The moon kept her company while the whole little neighborhood rested together."),
        story("olivia_color_hunt", "Olivia’s Colorful Morning", "A bright search through the garden.", StoryVisual.RAINBOW,
            "Olivia carried a little basket into the garden. She wondered how many colors she could find before breakfast.",
            "A red ladybug rested on a green leaf. Olivia looked closely and let it crawl away when it was ready.",
            "Near the fence, she found a yellow flower and a blue ribbon caught on a branch.",
            "She asked Eliana to help with the last color. Together they spotted a purple butterfly beside the lavender.",
            "Olivia placed one of each color in her basket, then returned every treasure to its cozy place.",
            "The garden still looked bright, and Olivia felt brighter too. Sharing the search made every color sparkle."),
        story("eliana_barnyard_day", "Eliana’s Barnyard Morning", "A friendly farm adventure with animal neighbors.", StoryVisual.DUCK,
            "Eliana visited the sunny farm with LooLoo. A duck quacked hello while a cow swished her tail by the gate.",
            "The pig had nudged a small bucket into the hay. Eliana and LooLoo gently rolled it back together.",
            "A sheep led them to the horse, who was waiting beside the water trough. Everyone seemed ready for breakfast.",
            "Eliana counted three scoops of grain. She shared them slowly so each friendly animal had a turn.",
            "The rooster crowed, the duck splashed, and the barnyard sounded like a happy little band.",
            "Eliana waved goodbye. The animals wiggled their ears as if to say, Come back tomorrow!"),
        story("sisters_lost_button", "The Button on the Breeze", "Two sisters solve a tiny garden mystery.", StoryVisual.PUPPY,
            "Olivia found a round blue button on the porch. Eliana wondered where it had come from.",
            "They followed a trail of tiny blue threads past the flowerpots and under a little chair in the sunny garden.",
            "A playful breeze lifted the button and sent it rolling toward LooLoo’s waiting basket nearby on the porch.",
            "Inside the basket was a teddy bear with one empty spot on its coat. The sisters knew at once.",
            "Olivia held the bear still while Eliana carefully tucked the button into place.",
            "The bear looked ready for a hug again. The sisters smiled at their small, helpful discovery."),
        story("olivia_eliana_cloud_boat", "The Cloud-Boat Trip", "An imaginative adventure above the rooftops.", StoryVisual.STAR,
            "Olivia and Eliana built a boat from cushions and pretended it could sail on the clouds.",
            "LooLoo became the captain. He pointed toward a fluffy cloud shaped like a sleepy whale.",
            "They sailed past a silver moonbeam and waved to birds flying home for the evening.",
            "A little cloud bumped their boat. Eliana offered it a soft pillow, and the cloud drifted happily beside them.",
            "Soon the pretend sea grew quiet. Olivia steered toward their living-room harbor.",
            "The sisters climbed out and hugged their captain. The best trips, they decided, can begin with one cushion."),
        story("eliana_counting_raindrops", "Eliana Counts the Raindrops", "A gentle rainy-day counting game.", StoryVisual.SNOWMAN,
            "Rain tapped the window while Eliana sat with LooLoo and watched the garden.",
            "One raindrop slid down the glass, then two more joined it in a shiny race.",
            "Eliana counted four drops on the left and five on the right. Olivia made a cheerful paper scoreboard.",
            "A sunny patch appeared, and the drops became tiny rivers. The sisters counted them again from the bottom.",
            "They lost track and laughed. Some raindrops were too quick to wait for counting.",
            "When the rain stopped, the garden glittered. Eliana decided that ten drops, or a hundred, were all beautiful."),
        story("looloo_silly_hat", "LooLoo’s Upside-Down Hat", "A giggly story about trying something new.", StoryVisual.SNOWMAN,
            "LooLoo put on a hat, but he placed it upside down. It sat on his ears like a tiny bowl.",
            "Olivia giggled kindly. Eliana found a spoon and pretended the hat was a soup pot.",
            "LooLoo marched around the room, stirring invisible moon soup with a sock.",
            "The hat slipped over his eyes, and he bumped softly into a cushion. Everyone laughed together.",
            "LooLoo turned the hat the right way and bowed like a chef. His soup was ready for pretend guests.",
            "The guests ate every invisible spoonful. LooLoo learned that a little silliness makes a big day."),
        story("kindness_kite", "The Kite That Shared the Sky", "A windy afternoon and a generous idea.", StoryVisual.RAINBOW,
            "Olivia brought a bright kite to the hill. Eliana held the string while the wind gave a gentle tug.",
            "A smaller child nearby watched quietly. The kite dipped low, almost close enough to touch.",
            "Olivia invited the child to hold the string. Eliana showed how to let it glide instead of pull.",
            "Up went the kite, red and gold against the blue sky. Three happy hands helped it dance.",
            "When the wind softened, they took turns bringing the kite home.",
            "The hill felt full of smiles. The kite had flown highest when everyone shared the fun."),
        story("farmyard_rainbow", "The Farmyard Rainbow", "Animals gather after a spring shower.", StoryVisual.DUCK,
            "A spring shower ended, and a rainbow appeared above the barn. The animals came out to see it.",
            "The cow found red in a berry patch. The pig spotted orange in a pumpkin by the fence.",
            "The sheep stood beside yellow buttercups, while the horse posed near green grass.",
            "A duck splashed through blue puddles. The rooster showed everyone a purple flower.",
            "Eliana and LooLoo counted six colors and clapped softly for their barnyard friends.",
            "The rainbow faded, but the animals stayed together. Their friendship made its own bright arch."),
        story("bedtime_lantern", "The Little Lantern’s Goodnight", "A cozy bedtime glow for a peaceful evening.", StoryVisual.STAR,
            "Eliana carried a little lantern to the window. Its warm glow made the room feel small and safe.",
            "Olivia tucked a blanket around LooLoo. Outside, the trees whispered softly to one another.",
            "The lantern shone on a book, a teddy bear, and three sleepy socks waiting for morning.",
            "Eliana took one slow breath. Olivia took one too, and the room grew quieter.",
            "The lantern did not need to shine brightly all night. Its gentle light was enough to say, You are safe.",
            "They closed their eyes together. The lantern kept its soft watch until the sun peeked in."),
        story("garden_helpers", "Olivia and Eliana Help the Garden", "A tiny garden grows with loving care.", StoryVisual.RAINBOW,
            "Olivia noticed the garden looked thirsty. Eliana carried a small watering can from the porch.",
            "They gave the seedlings gentle sips and left a shallow dish for a visiting bird.",
            "A snail was crossing the path. Eliana made a safe leaf bridge so no one would step on it.",
            "Olivia found one bent flower and tied it to a short stick for support.",
            "By afternoon, the leaves stood tall. The bird drank, and the snail reached the soft grass.",
            "The sisters sat beneath the tree. Helping the garden had made room for everyone to grow."),
    )
    fun find(id: String): Story? = stories.firstOrNull { it.id == id }
}
